import json, re, os

# Path to the raw source content file (generated by previous tool)
source_path = os.path.expanduser('/Users/idong-geon/.gemini/antigravity/brain/c3b4935f-0888-496c-bd8b-f0a6c534229a/.system_generated/steps/1155/output.txt')

if not os.path.exists(source_path):
    raise FileNotFoundError(f'Source file not found: {source_path}')

with open(source_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Split into weekly sections
weeks = re.split(r'REEFER MOVEMENT FOR (\d{2}/\d{2}/\d{2}) - (\d{2}/\d{2}/\d{2})', content)
# The split will produce a list where even indices are text before a week, and odd indices are start date, even indices after that are end date, etc.
# We'll iterate over matches using regex finditer instead for clarity.
entries = []
for match in re.finditer(r'REEFER MOVEMENT FOR (\d{2}/\d{2}/\d{2}) - (\d{2}/\d{2}/\d{2})(.*?)(?=REEFER MOVEMENT FOR|\Z)', content, re.S):
    start_date, end_date, block = match.groups()
    # The block contains rows of carriers and their deliveries.
    # Split by double newlines to separate carrier entries.
    carrier_blocks = [b.strip() for b in block.strip().split('\n\n') if b.strip()]
    for cb in carrier_blocks:
        lines = [ln.strip() for ln in cb.split('\n') if ln.strip()]
        if len(lines) < 2:
            continue
        carrier = lines[0]
        date = lines[1]
        deliveries = {}
        # Remaining lines are "COLUMN VALUE" pairs possibly with spaces.
        for line in lines[2:]:
            # split at first whitespace
            parts = line.split(None, 1)
            if len(parts) != 2:
                continue
            col, val = parts
            # Clean value: remove commas and keep as string
            deliveries[col] = val.replace(',', '')
        entries.append({
            "carrier": carrier,
            "date": date,
            "deliveries": deliveries
        })

# Output JSON
output_path = os.path.abspath('data/reeferMovementData.json')
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as out:
    json.dump(entries, out, ensure_ascii=False, indent=2)
print(f'Wrote {len(entries)} entries to {output_path}')
