import json

data = [
    {"id": 1, "company": "가나마린", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 1, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 2, "company": "경양수산", "total": 8, "tuna_longline": 8, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 3, "company": "경태", "total": 3, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 1, "squid_saury": 2, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 4, "company": "남궁튜나", "total": 2, "tuna_longline": 2, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 5, "company": "남북수산", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 1, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 6, "company": "대해수산", "total": 8, "tuna_longline": 8, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 7, "company": "동남", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 1, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 8, "company": "동신어업", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 1, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 9, "company": "동원산업", "total": 26, "tuna_longline": 11, "tuna_seine": 14, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 1, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 10, "company": "동원수산", "total": 14, "tuna_longline": 14, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 11, "company": "동원해사랑", "total": 4, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 1, "squid_saury": 3, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 12, "company": "사조대림", "total": 2, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 2, "other_trap": 0},
    {"id": 13, "company": "사조산업", "total": 32, "tuna_longline": 27, "tuna_seine": 5, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 14, "company": "사조씨푸드", "total": 3, "tuna_longline": 2, "tuna_seine": 1, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 15, "company": "사조오양", "total": 7, "tuna_longline": 3, "tuna_seine": 1, "trawl_north": 1, "trawl_pacific": 0, "trawl_atlantic": 2, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 16, "company": "선민수산", "total": 5, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 1, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 3, "squid_saury": 1, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 17, "company": "성경수산", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 1, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 18, "company": "승진수산", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 1, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 19, "company": "신라교역", "total": 15, "tuna_longline": 9, "tuna_seine": 6, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 20, "company": "신지수산", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 1},
    {"id": 21, "company": "신진피셔리", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 1, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 22, "company": "쓰리티오션", "total": 4, "tuna_longline": 4, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 23, "company": "씨맥스피셔리", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 1, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 24, "company": "아그네스수산", "total": 12, "tuna_longline": 4, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 2, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 6, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 25, "company": "에스앤비인터내셔널", "total": 2, "tuna_longline": 2, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 26, "company": "예람교역(비)", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 1, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 27, "company": "원양물산", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 1, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 28, "company": "정일산업", "total": 11, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 2, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 4, "squid_saury": 2, "saury": 0, "other_bottom": 0, "other_trap": 3},
    {"id": 29, "company": "참손푸드", "total": 2, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 2, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 30, "company": "창진교역", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 1, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 31, "company": "코삭교역", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 1, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 32, "company": "티엔에스산업", "total": 4, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 1, "other_trap": 3},
    {"id": 33, "company": "피에이아이", "total": 2, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 2, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 34, "company": "한성기업", "total": 5, "tuna_longline": 4, "tuna_seine": 0, "trawl_north": 1, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 35, "company": "해인수산", "total": 2, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 1, "squid_saury": 1, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 36, "company": "해천물산", "total": 7, "tuna_longline": 7, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 37, "company": "현원수산", "total": 1, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 1, "squid_saury": 0, "saury": 0, "other_bottom": 0, "other_trap": 0},
    {"id": 38, "company": "흥진실업", "total": 4, "tuna_longline": 0, "tuna_seine": 0, "trawl_north": 0, "trawl_pacific": 0, "trawl_atlantic": 0, "trawl_indian": 0, "trawl_antarctic": 0, "squid_jigging": 0, "squid_saury": 1, "saury": 0, "other_bottom": 1, "other_trap": 2}
]

with open('public/data/company_vessel_status.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("JSON file created successfully.")
